<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="41" errors="12" failures="0" skip="0"><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/common/openmtc/lib/aplus/__init__.py", line 6, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/common/openmtc/lib/coap/__init__.py", line 8, in <module>
    from aplus import Promise
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/common/openmtc/lib/aplus/__init__.py", line 6, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/common/openmtc/lib/lwm2m_lib/api/__init__.py", line 1, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/common/openmtc/src/openmtc/mapper/__init__.py", line 1, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named enum"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/common/openmtc/src/openmtc/model/__init__.py", line 4, in <module>
    from enum import Enum
ImportError: No module named enum
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named openmtc_app.onem2m"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/FrontEnd/test/test_frontEnd.py", line 1, in <module>
    from openmtc_app.onem2m import XAE
ImportError: No module named openmtc_app.onem2m
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/common/openmtc/lib/aplus/__init__.py", line 6, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/common/openmtc/lib/coap/__init__.py", line 8, in <module>
    from aplus import Promise
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/common/openmtc/lib/aplus/__init__.py", line 6, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/common/openmtc/lib/lwm2m_lib/api/__init__.py", line 1, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named futile.logging"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/common/openmtc/src/openmtc/mapper/__init__.py", line 1, in <module>
    from futile.logging import LoggerMixin
ImportError: No module named futile.logging
]]></error></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named enum"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/common/openmtc/src/openmtc/model/__init__.py", line 4, in <module>
    from enum import Enum
ImportError: No module named enum
]]></error></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__add_device_from_nd" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__add_device_from_rx" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__generate_simulated_data" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__get_device_handler" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__get_device_node_id" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__get_device_pid" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__get_sensor_handler" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__handle_ack" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__handle_device_data" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__handle_frame" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__handle_node_discover_frame" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__handle_rx_frame" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__handle_sensor_data" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__hex" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__parse_device_data" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__register_device" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__send_command_dev" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__send_node_discover" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__set_device_data" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__set_device_pid" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__set_tx_interval" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__time" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test__update_device_data" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test_add_handler" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test_get_simulated_device" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test_send_command_switch" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test_shutdown" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test_start" time="0.000"></testcase><testcase classname="eds.ZigBeeIPE.test.test_zigBeeCoordinator.TestZigBeeCoordinator" name="test_start_simulation" time="0.000"></testcase><testcase classname="nose.failure.Failure" name="runTest" time="0.000"><error type="exceptions.ImportError" message="No module named openmtc_app.onem2m"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/sro/Desktop/ElasTest/elastest-device-emulator-service/eds/ZigBeeIPE/test/test_zigBeeIPE.py", line 1, in <module>
    from openmtc_app.onem2m import XAE
ImportError: No module named openmtc_app.onem2m
]]></error></testcase></testsuite>